### ISSUE TITLE
[BUG] Cannot read file

### ISSUE THREAD

**Issue by Freymaurer** [CSBiology/FsSpreadsheet#42]
Tried reading file with FsSpreadsheet.ExcelIO.

```fsharp
#r "nuget: FsSpreadsheet"
#r "nuget: FsSpreadsheet.ExcelIO"

let path = @"C:/Users/Kevin/Desktop/Book1.xlsx"

open FsSpreadsheet
open FsSpreadsheet.ExcelIO

let wb = FsWorkbook.fromXlsxFile(path)
```

returns:

```cmd
> let wb = FsWorkbook.fromXlsxFile(path);;
System.InvalidOperationException: Error in implicit conversion. Cannot convert null object.
   at DocumentFormat.OpenXml.BooleanValue.op_Implicit(BooleanValue xmlAttribute)
   at FsSpreadsheet.ExcelIO.FsExtensions.FsTable.fromXlsxTable.Static(Table table)
   at FsSpreadsheet.ExcelIO.FsExtensions.sheets@185.Invoke(Sheet xlsxSheet)
   at Microsoft.FSharp.Collections.Internal.IEnumerator.map@128.DoMoveNext(b& curr) in D:\a\_work\1\s\src\FSharp.Core\seq.fs:line 134
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System.Collections.IEnumerator.MoveNext() in D:\a\_work\1\s\src\FSharp.Core\seq.fs:line 117
   at Microsoft.FSharp.Collections.SeqModule.Fold[T,TState](FSharpFunc`2 folder, TState state, IEnumerable`1 source) in D:\a\_work\1\s\src\FSharp.Core\seq.fs:line 914
   at FsSpreadsheet.ExcelIO.FsExtensions.FsWorkbook.fromXlsxFile.Static(String filePath)
   at <StartupCode$FSI_0017>.$FSI_0017.main@() in c:\Users\Kevin\Desktop\test.fsx:line 37
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
Stopped due to error
```

This is the file:
[Book1.xlsx](https://github.com/CSBiology/FsSpreadsheet/files/12157693/Book1.xlsx)

**Comment by HLWeil** [comment]
Anyone else looking into this? Otherwise I'll check

**Comment by Freymaurer** [comment]
Please do!
